apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap-main
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Hello World! Main page</title>
      </head>
      <body>
        <h1>Hello World! Main page</h1>
        <!--# set var="test" value="Hello stranger! SSI is on!" -->
        <!--# echo var="test" -->
        <!--# include virtual="/alpha" -->
        <!--# include virtual="/beta" -->
      </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap-alpha
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title></title>
        <h2>Hello World! SSI page 1</h2>
      </head>
      <body>
        <div id="test"></div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap-beta
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title></title>
        <h2>Hello World! SSI page 2</h2>
      </head>
      <body>
        <div id="test"></div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-main
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;
    events {
      worker_connections  1024;
    }
    http {
      keepalive_timeout  65;
      gzip  on;

      server {
        listen       80;
        server_name  localhost;
        ssi on;
        ssi_silent_errors off;
        proxy_set_header Accept-Encoding "";

        proxy_intercept_errors on;
        proxy_ssl_server_name on;
        
        location / {
          root   /usr/share/nginx/html; #Change this line
          index  index.html index.htm;
        }

        location /alpha {
          proxy_pass http://alpha.default.svc.cluster.local/;
        }

        location /beta {
          proxy_pass http://beta.default.svc.cluster.local/;
        }

      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: main
  name: main
  namespace: default
spec:
  containers:
  - name: common
    image: nginx:1.21.6-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: nginx-index-file
        mountPath: /usr/share/nginx/html/
      - name: nginx-conf
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
        readOnly: true
  volumes:
  - name: nginx-index-file
    configMap:
      name: index-html-configmap-main
  - name: nginx-conf
    configMap:
      name: nginx-main
      items:
        - key: nginx.conf
          path: nginx.conf
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: alpha
    app.kubernetes.io/name: alpha
  name: alpha
  namespace: default
spec:
  containers:
  - name: common
    image: nginx:1.21.6-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: nginx-index-file
        mountPath: /usr/share/nginx/html/
  volumes:
  - name: nginx-index-file
    configMap:
      name: index-html-configmap-alpha
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: beta
    app.kubernetes.io/name: beta
  name: beta
  namespace: default
spec:
  containers:
  - name: common
    image: nginx:1.21.6-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: nginx-index-file
        mountPath: /usr/share/nginx/html/
  volumes:
  - name: nginx-index-file
    configMap:
      name: index-html-configmap-beta
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: alpha
    app.kubernetes.io/name: alpha
  name: alpha
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: alpha
    app.kubernetes.io/name: alpha
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: beta
    app.kubernetes.io/name: beta
  name: beta
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: beta
    app.kubernetes.io/name: beta
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: main
  name: main
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: main
  type: ClusterIP
